<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BeneficiarySeeder extends Seeder
{
    public function run(): void
    {
        $beneficiaries = [
            [
                'registration_number' => 'BEN2023001',
                'full_name' => 'Andi Pratama',
                'nickname' => 'Andi',
                'date_of_birth' => '2012-05-15',
                'place_of_birth' => 'Jakarta',
                'gender' => 'L',
                'blood_type' => 'O',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Ibu Siti',
                'emergency_phone' => '081234567001',
                'emergency_relation' => 'Bibi',
                'entry_date' => '2023-01-10',
                'status' => 'Active',
                'education_level' => 'SD Kelas 5',
                'school_name' => 'SD Negeri 1 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023002',
                'full_name' => 'Siti Nurhaliza',
                'nickname' => 'Siti',
                'date_of_birth' => '2011-08-20',
                'place_of_birth' => 'Bandung',
                'gender' => 'P',
                'blood_type' => 'A',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Pak Joko',
                'emergency_phone' => '081234567002',
                'emergency_relation' => 'Paman',
                'entry_date' => '2023-01-15',
                'status' => 'Active',
                'education_level' => 'SD Kelas 6',
                'school_name' => 'SD Negeri 2 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023003',
                'full_name' => 'Budi Santoso',
                'nickname' => 'Budi',
                'date_of_birth' => '2013-03-12',
                'place_of_birth' => 'Surabaya',
                'gender' => 'L',
                'blood_type' => 'B',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Ibu Ani',
                'emergency_phone' => '081234567003',
                'emergency_relation' => 'Nenek',
                'entry_date' => '2023-02-01',
                'status' => 'Active',
                'education_level' => 'SD Kelas 4',
                'school_name' => 'SD Negeri 1 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023004',
                'full_name' => 'Dewi Lestari',
                'nickname' => 'Dewi',
                'date_of_birth' => '2012-11-08',
                'place_of_birth' => 'Malang',
                'gender' => 'P',
                'blood_type' => 'AB',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Pak Ahmad',
                'emergency_phone' => '081234567004',
                'emergency_relation' => 'Kakek',
                'entry_date' => '2023-02-10',
                'status' => 'Active',
                'education_level' => 'SD Kelas 5',
                'school_name' => 'SD Negeri 3 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023005',
                'full_name' => 'Rudi Hermawan',
                'nickname' => 'Rudi',
                'date_of_birth' => '2014-01-25',
                'place_of_birth' => 'Semarang',
                'gender' => 'L',
                'blood_type' => 'O',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Ibu Maria',
                'emergency_phone' => '081234567005',
                'emergency_relation' => 'Tante',
                'entry_date' => '2023-03-05',
                'status' => 'Active',
                'education_level' => 'SD Kelas 3',
                'school_name' => 'SD Negeri 1 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023006',
                'full_name' => 'Fitri Handayani',
                'nickname' => 'Fitri',
                'date_of_birth' => '2013-06-18',
                'place_of_birth' => 'Yogyakarta',
                'gender' => 'P',
                'blood_type' => 'A',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Pak Bambang',
                'emergency_phone' => '081234567006',
                'emergency_relation' => 'Om',
                'entry_date' => '2023-03-15',
                'status' => 'Active',
                'education_level' => 'SD Kelas 4',
                'school_name' => 'SD Negeri 2 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023007',
                'full_name' => 'Agus Setiawan',
                'nickname' => 'Agus',
                'date_of_birth' => '2012-09-30',
                'place_of_birth' => 'Solo',
                'gender' => 'L',
                'blood_type' => 'B',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Ibu Rina',
                'emergency_phone' => '081234567007',
                'emergency_relation' => 'Tante',
                'entry_date' => '2023-04-01',
                'status' => 'Active',
                'education_level' => 'SD Kelas 5',
                'school_name' => 'SD Negeri 3 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'BEN2023008',
                'full_name' => 'Rina Wijaya',
                'nickname' => 'Rina',
                'date_of_birth' => '2011-12-05',
                'place_of_birth' => 'Bekasi',
                'gender' => 'P',
                'blood_type' => 'O',
                'religion' => 'Islam',
                'address' => 'Bandung',
                'emergency_contact' => 'Pak Hadi',
                'emergency_phone' => '081234567008',
                'emergency_relation' => 'Paman',
                'entry_date' => '2023-04-10',
                'status' => 'Active',
                'education_level' => 'SD Kelas 6',
                'school_name' => 'SD Negeri 1 Bandung',
                'location_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('beneficiaries')->insert($beneficiaries);
        $this->command->info('✓ Beneficiaries seeded successfully!');
    }
}
