<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DonationSeeder extends Seeder
{
    public function run(): void
    {
        $donations = [
            [
                'donation_code' => 'DON' . date('Ymd') . '001',
                'donor_name' => 'PT. Cahaya Abadi',
                'donor_type' => 'Company',
                'donor_email' => 'csr@cahayaabadi.com',
                'donor_phone' => '021-12345678',
                'amount' => 10000000,
                'donation_date' => Carbon::now()->subDays(10),
                'payment_method' => 'Transfer',
                'payment_reference' => 'TRF001234567',
                'status' => 'Completed',
                'purpose' => 'Pembangunan Rumah Singgah',
                'program_id' => null,
                'is_recurring' => false,
                'is_anonymous' => false,
                'receipt_sent' => true,
                'receipt_number' => 'RCP2025001',
                'verified_by' => 3,
                'verified_at' => Carbon::now()->subDays(9),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'donation_code' => 'DON' . date('Ymd') . '002',
                'donor_name' => 'Ibu Sinta Dewi',
                'donor_type' => 'Individual',
                'donor_email' => 'sinta@email.com',
                'donor_phone' => '081234567890',
                'amount' => 2000000,
                'donation_date' => Carbon::now()->subDays(5),
                'payment_method' => 'Online',
                'payment_reference' => 'ONLINE789456',
                'status' => 'Completed',
                'purpose' => 'Pendidikan Anak Asuh',
                'program_id' => 1,
                'is_recurring' => true,
                'is_anonymous' => false,
                'receipt_sent' => true,
                'receipt_number' => 'RCP2025002',
                'verified_by' => 3,
                'verified_at' => Carbon::now()->subDays(4),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'donation_code' => 'DON' . date('Ymd') . '003',
                'donor_name' => 'Donatur Anonim',
                'donor_type' => 'Individual',
                'donor_email' => null,
                'donor_phone' => null,
                'amount' => 5000000,
                'donation_date' => Carbon::now()->subDays(3),
                'payment_method' => 'Transfer',
                'payment_reference' => 'TRF999888777',
                'status' => 'Completed',
                'purpose' => 'Bantuan Umum',
                'program_id' => null,
                'is_recurring' => false,
                'is_anonymous' => true,
                'receipt_sent' => false,
                'receipt_number' => null,
                'verified_by' => 3,
                'verified_at' => Carbon::now()->subDays(2),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'donation_code' => 'DON' . date('Ymd') . '004',
                'donor_name' => 'Yayasan Peduli Anak',
                'donor_type' => 'Organization',
                'donor_email' => 'info@pedulianak.org',
                'donor_phone' => '021-87654321',
                'amount' => 15000000,
                'donation_date' => Carbon::now()->subDays(15),
                'payment_method' => 'Check',
                'payment_reference' => 'CHK001122',
                'status' => 'Completed',
                'purpose' => 'Program Keterampilan',
                'program_id' => 2,
                'is_recurring' => false,
                'is_anonymous' => false,
                'receipt_sent' => true,
                'receipt_number' => 'RCP2025003',
                'verified_by' => 3,
                'verified_at' => Carbon::now()->subDays(14),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'donation_code' => 'DON' . date('Ymd') . '005',
                'donor_name' => 'Pak Budi Santoso',
                'donor_type' => 'Individual',
                'donor_email' => 'budi@email.com',
                'donor_phone' => '081298765432',
                'amount' => 1000000,
                'donation_date' => Carbon::now()->subDay(),
                'payment_method' => 'Online',
                'payment_reference' => 'ONLINE123456',
                'status' => 'Verified',
                'purpose' => 'Konseling Psikologi',
                'program_id' => 3,
                'is_recurring' => true,
                'is_anonymous' => false,
                'receipt_sent' => false,
                'receipt_number' => null,
                'verified_by' => 3,
                'verified_at' => Carbon::now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('donations')->insert($donations);
        $this->command->info('✓ Donations seeded successfully!');
    }
}
